import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import React from "react";
import "./globals.css";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  blog
}: Readonly<{
  children: React.ReactNode;
  blog: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {blog}
        {children}
      </body>
    </html>
  );
}
